name: Copy into clone repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
  ORG_GIT_URL: git@github.com:fawad

jobs:
  copy_in_clone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        repository: fawad/workflow-test-repo
        token: ${{ secrets.ACCESS_TOKEN_FOR_WORKFLOWS }}
    - name: Sync main branches
      run: |
        git clone ${{ env.ORG_GIT_URL }}/${{ env.ORIGINAL_REPO_NAME }}-repo.git
        cd ${{ env.ORIGINAL_REPO_NAME }}
        git remote add ${{ env.ORIGINAL_REPO_NAME }} ${{ github.event.repository.ssh_url }}
        git remote update
        git merge ${{ env.ORIGINAL_REPO_NAME }}/main
        git push origin main
