name: Copy into clone repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
  ORG_GIT_URL: git@github.com:fawad

jobs:
  copy_in_clone:
    runs-on: ubuntu-latest
    steps:
    - name: Sync main branches
      run: |
        git clone https://fawad:${{ secrets.ACCESS_TOKEN_FOR_WORKFLOWS }}@github.com/fawad/workflow-test-repo.git
        cd workflow-test-repo
        git remote add ${{ env.ORIGINAL_REPO_NAME }} ${{ github.event.repository.ssh_url }}
        git remote update
        git merge ${{ env.ORIGINAL_REPO_NAME }}/main
        git push origin main
