name: Copy into clone repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
  ORG_GIT_URL: git@github.com:fawad

jobs:
  copy_in_clone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: fawad/workflow-test-repo
        token: ${{ secrets.ACCESS_TOKEN_FOR_WORKFLOWS }}
        path: './repo'
    - name: Sync main branches
      run: |
        git remote add ${{ env.ORIGINAL_REPO_NAME }} ${{ github.event.repository.ssh_url }}
        git remote update
        git merge ${{ env.ORIGINAL_REPO_NAME }}/main
        git push origin main
