name: Copy into clone repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
  ORG_GIT_URL: git@github.com:almana-agh

jobs:
  copy_in_clone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Sync main branches
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        echo "repo is $ORG_GIT_URL/$ORIGINAL_REPO_NAME-repo.git"
        ssh -T git@github.com
