name: Copy into clone repo

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
  ORG_GIT_URL: git@github.com:almana-agh

jobs:
  copy_in_clone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Sync main branches
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
        git clone "$ORG_GIT_URL/$ORIGINAL_REPO_NAME-repo.git"
        cd $ORIGINAL_REPO_NAME
        git remote add $ORIGINAL_REPO_NAME ${{ github.event.repository.ssh_url }}
        git remote update
        git merge $ORIGINAL_REPO_NAME/main
        git push origin main
